version: "3.9"

services:
  spring-rest-api-mysql:
    container_name: "spring-rest-api-mysql"
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: spring-rest-api
      MYSQL_ROOT_PASSWORD: root